// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjgwobbcnxtfzqmozlwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ3dvYmJjbnh0ZnpxbW96bHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTUwMjIsImV4cCI6MjA1MDYzMTAyMn0.OaC0oVPbdMuiS0evltMH0hsVjArlsEWxh_wcU5iq7Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);